function eegSpectrogram_v2(data_matrix, Fs, emg_row_idx, params, file_label)
% eegSpectrogram_v2  Expanded multi-channel EEG/EMG visualiser
%
%   eegSpectrogram_v2(DATA_MATRIX, FS, EMG_ROW_IDX, PARAMS, FILE_LABEL)
%
%   INPUTS
%     data_matrix   : numeric matrix (channels x samples)
%     Fs            : sampling rate (Hz)
%     emg_row_idx   : row index corresponding to EMG channel. If empty or
%                     NaN the user will be prompted to enter the row.
%     params        : struct with optional fields
%                       .fMaxEEG_spec (default 50)
%                       .fMaxEMG_spec (default 150)
%                       .winSecSpec   (default 0.256)
%                       .overlapRatio (default 0.90)
%     file_label    : string used in the figure window title
%
%   The function assumes that all rows *except* the EMG row are EEG
%   channels. It generates a figure containing two columns:
%     • Left  : time-domain filtered EEG/EMG traces
%     • Right : log10-amplitude spectrograms for each channel
%
%   NOTE
%   -------
%   This function requires computeLogSpectrogram.m to be available on the
%   MATLAB path.
%
%   Author: auto-generated by GPT-4 — 2025-07-07
%

% ------------------ Handle missing inputs interactively ------------------
if nargin < 1 || isempty(data_matrix)
    [file_name, path_name] = uigetfile({'*.mat','MAT-files'}, 'Select data file');
    if isequal(file_name,0)
        error('No file selected.');
    end
    loaded_struct = load(fullfile(path_name, file_name));
    % Try common field names
    fNames = fieldnames(loaded_struct);
    data_matrix = [];
    for fn = 1:numel(fNames)
        candidate = loaded_struct.(fNames{fn});
        if isnumeric(candidate) && ndims(candidate)==2 && size(candidate,1) >= 5 && size(candidate,2) > 10
            data_matrix = candidate;
            break;
        end
    end
    if isempty(data_matrix)
        error('Could not find a 2-D numeric matrix inside the selected .mat file.');
    end
    fprintf('Loaded data matrix from %s (size: %dx%d)\n', fNames{fn}, size(data_matrix,1), size(data_matrix,2));
    % Auto-set label from filename if not provided later
    if nargin < 5
        file_label = file_name;
    end
end

if nargin < 2 || isempty(Fs)
    Fs = input('Enter sampling rate (Hz): ');
    if isempty(Fs) || ~isnumeric(Fs) || Fs<=0
        error('Invalid sampling rate.');
    end
end

% emg_row_idx will be handled later (already prompts if invalid)
% params and file_label defaults are already set further below

%% ------------------------- Input validation -------------------------- %%
validateattributes(data_matrix, {'numeric'}, {'2d', 'nonempty'}, mfilename, 'data_matrix', 1);

% Enforce exactly five rows: 4 EEG + 1 EMG
n_channels = size(data_matrix, 1);
if n_channels ~= 5
    error("eegSpectrogram_v2 expects DATA_MATRIX with 5 rows (4 EEG + 1 EMG). Provided matrix has %d rows.", n_channels);
end

validateattributes(Fs,          {'numeric'}, {'scalar', 'positive'}, mfilename, 'Fs',          2);

% Ask for EMG row if not provided or invalid
if nargin < 3 || isempty(emg_row_idx) || ~isscalar(emg_row_idx) || ...
        emg_row_idx < 1 || emg_row_idx > n_channels || isnan(emg_row_idx)
    fprintf("Available channel rows: 1 .. %d\n", n_channels);
    emg_row_idx = input("Enter the row number corresponding to EMG channel: ");
    if isempty(emg_row_idx) || emg_row_idx < 1 || emg_row_idx > n_channels
        error("Invalid EMG row specified.");
    end
end

% Parameter defaults
if nargin < 4 || isempty(params)
    params = struct();
end
if ~isfield(params, "fMaxEEG_spec"), params.fMaxEEG_spec = 50; end
if ~isfield(params, "fMaxEMG_spec"), params.fMaxEMG_spec = 150; end
if ~isfield(params, "winSecSpec"  ), params.winSecSpec   = 0.256; end
if ~isfield(params, "overlapRatio"), params.overlapRatio = 0.90; end

if nargin < 5 || isempty(file_label)
    file_label = "eegSpectrogram";
end

%% -------------------- Setup spectrogram parameters ------------------- %%
winSecSpec   = params.winSecSpec;
winSpec      = round(winSecSpec * Fs);
noverlapSpec = round(params.overlapRatio * winSpec);

%% ----------------- Identify EEG and EMG channel indices -------------- %%
EEG_rows = setdiff(1:n_channels, emg_row_idx);
if isempty(EEG_rows)
    error("No EEG channels found (all rows other than EMG are considered EEG).");
end

%% ------------------- Band-pass filter design (1-100 Hz) -------------- %%
[b_filt, a_filt] = butter(4, [1 100]/(Fs/2), "bandpass");

%% -------------------------- Figure setup ----------------------------- %%
figure('Name', sprintf('EEG/EMG Spectrogram – %s', file_label), ...
       'Color', 'w', 'NumberTitle', 'off');

grid_rows = numel(EEG_rows) + 1;   % +1 for EMG row

plot_idx = 1;

%% ------------------------- EEG channels ------------------------------ %%
for ii = 1:numel(EEG_rows)
    row_idx = EEG_rows(ii);
    sig_raw = double(data_matrix(row_idx, :));
    t = (0:numel(sig_raw)-1)/Fs;

    % Filter for plotting
    sig_filt = filtfilt(b_filt, a_filt, sig_raw);

    % --- Left subplot: time-domain trace ---
    subplot(grid_rows, 2, plot_idx);
    plot(t, sig_filt, 'k');
    xlabel('Time (s)'); ylabel('\muV'); grid on; axis tight;
    title(sprintf('EEG Row %d – Filtered (1-100 Hz)', row_idx));

    % --- Right subplot: spectrogram ---
    subplot(grid_rows, 2, plot_idx+1);
    [f, t_spec, logSpec] = computeLogSpectrogram(sig_raw, Fs, winSpec, noverlapSpec, params.fMaxEEG_spec);
    imagesc(t_spec, f, logSpec);
    axis xy; colormap jet; caxis(log10([1e-1 1e3]));
    ylabel('Frequency (Hz)'); xlabel('Time (s)');
    title(sprintf('EEG Row %d – Spectrogram', row_idx));
    colorbar('eastoutside');

    plot_idx = plot_idx + 2;
end

%% ------------------------------ EMG --------------------------------- %%
% Process EMG similarly
sig_emg_raw = double(data_matrix(emg_row_idx, :));

t = (0:numel(sig_emg_raw)-1)/Fs;
sig_emg_filt = filtfilt(b_filt, a_filt, sig_emg_raw);

subplot(grid_rows, 2, plot_idx);
plot(t, sig_emg_filt, 'Color', [0.4 0.4 0.4]);
xlabel('Time (s)'); ylabel('\muV'); grid on; axis tight;
title(sprintf('EMG Row %d – Filtered (1-100 Hz)', emg_row_idx));

subplot(grid_rows, 2, plot_idx+1);
[f_emg, t_emg, logSpec_emg] = computeLogSpectrogram(sig_emg_raw, Fs, winSpec, noverlapSpec, params.fMaxEMG_spec);
imagesc(t_emg, f_emg, logSpec_emg);
axis xy; colormap jet; caxis(log10([1e-1 1e3]));
ylabel('Frequency (Hz)'); xlabel('Time (s)');
title(sprintf('EMG Row %d – Spectrogram', emg_row_idx));
cb = colorbar('eastoutside'); ylabel(cb, 'log_{10}(\muV / \surdHz)');

%% --------------------------- Final tweaks ---------------------------- %%
sgtitle(sprintf('EEG/EMG Analysis – %s', strrep(file_label, '_', '\_')), 'FontWeight', 'bold');
end 